export function transferToAlunoHtml(valor: number, motivo: string) {
	return `<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;"><div style="background-color: #1e40af; color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center;"><h1 style="margin: 0; font-size: 24px;">💰 BNP Coin</h1></div><div style="background-color: white; padding: 30px; border-radius: 0 0 8px 8px;"><h2 style="color: #1e40af; margin-top: 0;">Parabéns!</h2><p style="font-size: 16px; color: #333;">Você recebeu <strong style="color: #1e40af; font-size: 20px;">${valor} BNP Coins</strong></p><div style="background-color: #eff6ff; padding: 15px; border-left: 4px solid #1e40af; margin: 20px 0;"><p style="margin: 0; color: #1e40af;"><strong>Motivo:</strong> ${motivo}</p></div><p style="color: #666; font-size: 14px;">Continue se dedicando para ganhar mais moedas!</p></div></div>`;
}

export function transferToProfessorHtml(valor: number, motivo: string, novoSaldoProfessor: number) {
	return `<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;"><div style="background-color: #1e40af; color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center;"><h1 style="margin: 0; font-size: 24px;">💰 BNP Coin</h1></div><div style="background-color: white; padding: 30px; border-radius: 0 0 8px 8px;"><h2 style="color: #1e40af; margin-top: 0;">Transferência Realizada</h2><p style="font-size: 16px; color: #333;">Você transferiu <strong style="color: #1e40af; font-size: 20px;">${valor} BNP Coins</strong></p><div style="background-color: #eff6ff; padding: 15px; border-left: 4px solid #1e40af; margin: 20px 0;"><p style="margin: 0; color: #1e40af;"><strong>Motivo:</strong> ${motivo}</p></div><p style="color: #666; font-size: 14px;">Seu saldo atual: <strong>${novoSaldoProfessor} BNP Coins</strong></p></div></div>`;
}

export function resgateAlunoHtml(vantagemDescricao: string, valorVantagem: number, codigoResgate: string) {
	return `<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;"><div style="background-color: #1e40af; color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center;"><h1 style="margin: 0; font-size: 24px;">💰 BNP Coin</h1></div><div style="background-color: white; padding: 30px; border-radius: 0 0 8px 8px;"><h2 style="color: #1e40af; margin-top: 0;">🎉 Resgate Realizado com Sucesso!!!</h2><p style="font-size: 16px; color: #333;">Parabéns! Você resgatou a seguinte vantagem:</p><div style="background-color: #f0f7ff; padding: 20px; border-left: 4px solid #1e40af; margin: 20px 0; border-radius: 4px;"><p style="margin: 0; color: #333; font-size: 18px;"><strong>${vantagemDescricao}</strong></p><p style="margin: 10px 0 0 0; color: #666; font-size: 14px;">Custo: <strong>${valorVantagem} BNP Coins</strong></p></div><h3 style="color: #1e40af; margin-top: 30px; text-align: center;">Código de Resgate</h3><div style="text-align: center; margin: 20px 0;"><img src="cid:qrcode" alt="QR Code de Resgate" style="width: 200px; height: 200px; border: 2px solid #1e40af; border-radius: 4px;" /></div><p style="text-align: center; color: #333; font-size: 14px; word-break: break-all;"><strong>Código:</strong> ${codigoResgate}</p><div style="background-color: #fff3cd; padding: 15px; border-left: 4px solid #ffc107; margin: 20px 0; border-radius: 4px;"><p style="margin: 0; color: #856404;"><strong>⚠️ Importante:</strong> Apresente este QR Code ou o código acima quando for utilizar sua vantagem.</p></div><p style="color: #666; font-size: 14px; margin-top: 30px; border-top: 1px solid #eee; padding-top: 20px;">Obrigado por usar BNP Coin! Aproveite sua vantagem! 🎁</p></div></div>`;
}

export function resgateEmpresaHtml(vantagemDescricao: string, valorVantagem: number, codigoResgate: string) {
	return `<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;"><div style="background-color: #1e40af; color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center;"><h1 style="margin: 0; font-size: 24px;">💰 BNP Coin</h1></div><div style="background-color: white; padding: 30px; border-radius: 0 0 8px 8px;"><h2 style="color: #1e40af; margin-top: 0;">📦 Vantagem Resgatada!</h2><p style="font-size: 16px; color: #333;">Uma vantagem foi resgatada pela sua empresa:</p><div style="background-color: #f0f7ff; padding: 20px; border-left: 4px solid #1e40af; margin: 20px 0; border-radius: 4px;"><p style="margin: 0; color: #333; font-size: 18px;"><strong>${vantagemDescricao}</strong></p><p style="margin: 10px 0 0 0; color: #666; font-size: 14px;">Valor: <strong>${valorVantagem} BNP Coins</strong></p></div><h3 style="color: #1e40af; margin-top: 30px; text-align: center;">Código de Resgate</h3><div style="background-color: #f0f7ff; padding: 20px; border-left: 4px solid #1e40af; margin: 20px 0; border-radius: 4px; text-align: center;"><p style="margin: 0; color: #333; font-size: 16px; word-break: break-all;"><strong style="display: block; color: #1e40af; margin-bottom: 10px;">Código:</strong><span style="font-family: monospace; font-size: 14px; color: #1e40af;">${codigoResgate}</span></p></div><div style="background-color: #e8f4f8; padding: 15px; border-left: 4px solid #1e40af; margin: 20px 0; border-radius: 4px;"><p style="margin: 0; color: #0a5a7d;"><strong>💡 Próximos passos:</strong> Aguarde o cliente apresentar este código para validar o resgate da vantagem.</p></div><p style="color: #666; font-size: 14px; margin-top: 30px; border-top: 1px solid #eee; padding-top: 20px;">Obrigado por participar do programa BNP Coin! 🎁</p></div></div>`;
}
